### ISSUE TITLE
Visiting a profile from your profile keeps edit buttons

### ISSUE THREAD

**Issue by pixeldesu** [hummingbird-me/hummingbird#496]
If you visit another users profile page after being on yours (that user is a follower/you follow them), the edit buttons and actions remain on the other users profile.

Example:
![](http://a.pomf.se/zbpkjp.png)

**Comment by vevix** [comment]
Can you consistently reproduce this? I can't seem to reproduce it at all :confused:

**Comment by pixeldesu** [comment]
I just realized, as there are 3 conditions on how to get to another users profile over these cards:

* **clicking the profile picture** doesn't show the edit button on the other users profile
* **clicking the profile header** will show the edit button
* **clicking the username** will show the edit button

I'm using Chromium 41.0.2272.101 (64-bit) on Chakra Linux, also reproduced this on Firefox 37.0.1 on the same system.

[Here's a recording of the issue, trying out all 3 ways of accessing a profile](http://file.pixelde.su/hummingbird-profile.webm)

It seems, that only clicking the profile picture reloads the page, clicking the name or the header just fast-loads (and replaces) the content, but keeps the button from the initial profile.

**Comment by vevix** [comment]
We don't really ever refresh the page on Hummingbird, new content is requested over XHR and replaced on the page.

I still can't reproduce this on Windows 8.1 Chrome 41 & Firefox 34/35 :confused: Check your Chromium JavaScript console for any errors that may be causing this.

/cc @NuckChorris @cybrox

**Comment by cybrox** [comment]
I can't seem to reproduce this with Chrome 44/dev on Windows 7 either. Any of the possible clickable elements to get to a user's page reloads it correctly for me.

**Comment by vevix** [comment]
Okay, I still can't reproduce this.

@pixeldesu Could you provide us with some screenshots of both the JavaScript console, and the Network information tab when this happens?

https://developer.chrome.com/devtools#access

**Comment by Eschon** [comment]
I think I managed to reproduce this.

1. Go to Following or Followers on your Profile.
![1](https://cloud.githubusercontent.com/assets/11647830/7669626/6f5a2dde-fc7e-11e4-89fe-7924b6ec6877.PNG)

2. Click on anybody that shows up in that list. The background and the content change but the menu stays the same.
![2](https://cloud.githubusercontent.com/assets/11647830/7669631/89d5d3e8-fc7e-11e4-8e02-1e0553db5e1c.PNG)


Here is the output of JavaScript console and Network information:
![3](https://cloud.githubusercontent.com/assets/11647830/7669632/9bc8e4fa-fc7e-11e4-99e4-5def544bea0c.PNG)

![4](https://cloud.githubusercontent.com/assets/11647830/7669633/9e4fa4e8-fc7e-11e4-9657-5d0836b336e5.PNG)

I hope that helps.

**Comment by vevix** [comment]
What version of Firefox? Still can't reproduce this.

**Comment by Eschon** [comment]
Oh sorry forgot to mention it. Its Firefox 38.0.1

**Comment by Eschon** [comment]
I just tested some other browsers and it also happens to me when using Google Chrome 42.0.2311.152 and Firefox Developer (40.0a2).

But I also asked a friend of mine to test this and it doesn't happen for him. He uses Google Chrome, same version as I.

**Comment by vevix** [comment]
Mmm odd, do you have any addons? Try disabling them

**Comment by erengy** [comment]
I'm able to reproduce this issue, both on Firefox 40.0a2 (logged in, with add-ons) and Chrome 42.0.2311.152 (not logged in, no extensions). The cover photo and the page content changes, but the user avatar, name, bio and profile navigation buttons stay the same.

The console for Chrome is as following:

![](https://cloud.githubusercontent.com/assets/1078430/7670006/d0902322-fc99-11e4-9998-44b34c33e361.png)

**Comment by Eschon** [comment]
> Mmm odd, do you have any addons?
I have some in Firefox (38) but I have none in Chrome and Firefox 40

Maybe this has something to do with the account.

**Comment by vevix** [comment]
I see 2 errors from 2 people on pro.js, what file is that from?

**Comment by erengy** [comment]
It's from https://s3.buysellads.com/ac/pro.js

**Comment by wopian** [comment]
You get message-bus errors because its currently disabled.

**Comment by DNA** [comment]
I can confirm this bug too. 

I've also compiled a list of reports, to see if we can see some pattern:

| User       | Confirm? | Browser  | Version       | SO          | Logged? | Addon? |
|------------|:--------:|----------|---------------|-------------|:-------:|:------:|
| @cybrox    | No       | Chrome   | 44/dev        | Windows 7   | ?       | ?      |
| @vevix     | No       | Chrome   | 41            | Windows 8.1 | ?       | ?      |
| @vevix     | No       | Firefox  | 34/35         | Windows 8.1 | ?       | ?      |
| @pixeldesu | Yes      | Chromium | 41.0.2272.101 | Linux       | ?       | ?      |
| @Eschon    | Yes      | Chrome   | 42.0.2311.152 | ?           | ?       | No     |
| @erengy    | Yes      | Chrome   | 42.0.2311.152 | ?           | No      | No     |
| @DNA       | Yes      | Chrome   | 43.0.2357.81  | os X 10.3   | Yes     | Yes    |
| @pixeldesu | Yes      | Firefox  | 37.0.1        | Linux       | ?       | ?      |
| @DNA       | Yes      | Firefox  | 38.0.1        | os X 10.3   | Yes     | No     |
| @Eschon    | Yes      | Firefox  | 38.0.1        | ?           | ?       | Yes    |
| @Eschon    | Yes      | Firefox  | 40.0a2        | ?           | ?       | No     |
| @Eschon    | Yes      | Firefox  | 40.0a2        | ?           | Yes     | Yes    |

**Comment by wopian** [comment]
User | Confirm? | Browser | Version | OS | Logged? | Addon?
------------ | -------------
@wopian | No | Chrome | 45.0.2414.0 dev-m | Windows 8.1 Pro | Yes | No

**Comment by DNA** [comment]
Updated the table. Also, tested with login on and off, but doesn't seems to have any difference…

**Comment by Eschon** [comment]
@DNA for your table: I use Windows 7 Professional

**Comment by wopian** [comment]
Not quite the same as OP but I managed to replicate it constantly on Chrome 43.0.2357.81 m running Windows 7 Professional.

Visiting any profiles from my followers page (https://hummingbird.me/users/wopian/followers) keeps all of my content in the cover area.

**Comment by TillaTheHun0** [comment]
Replicated @pixeldesu 3 cases in Chrome 43.0.2357.65 on OSX 10.10.3. The cover art will change, but the original profile picture, along with the edit button is still visible.

**Comment by vevix** [comment]
I just tried Chrome, Firefox, Firefox Developer Edition, Safari, Internet Explorer, and Opera over Windows 8.1 & OS X 10.3.

I can only reproduce this while I am logged out, or logged into a non-admin account. Hopefully I can take a look at this tomorrow night.

**Comment by DNA** [comment]
Damn, talk about a quite specific bug to catch… xD

Now that the javascript guys can reproduce the bug, I'll stop updating the table :P

**Comment by link07** [comment]
I noticed this bug when I clicked on my "Following" button and clicked on a friend, my Avatar / Username / tag, but the cover changed.  When I f5'd, his showed, so I started experimenting, and it appears to me like whenever you go to a new profile from Following and Followers it doesn't update those things.

I started out in a [new tab with a clean console](http://i.imgur.com/lJOynKi.jpg), and then went to following and [selected a different user](http://i.imgur.com/Z2d5uOV.jpg), as you can see from that second screenshot, it still has Alto's username, picture, and tagline, yet I'm on Sabre's page.  Looking in the console fully, I get a [ton of error messages, even minutes after loading the page](http://pastebin.com/TqkF90Ph), most of them seem to be just reporting that some stuff is loading over https and some is over http, no big deal; but the early errors are the important ones [here](http://i.imgur.com/n9WNDGm.png) is the sub info from chrome.

The screenshots are from an icogneto window in chrome, with a disabled ublock origin (I keep it disabled on hummingbird :)) and lastpass password manager, which shouldn't be interacting with that page at all.  I noticed it while logged in with many other extensions.
https://github.com/hummingbird-me/hummingbird/issues/496#fullscreen

User	 | Confirm? |Browser | Version | OS | Logged? | Addon?
------------ | ------------- | ------------ | ------------- | ------------ | -------------| ------------
[Link07](http://hummingbird.me/users/link07) & [Alto](http://hummingbird.me/users/alto) | Yes | Chrome | 43.0.2357.132 64bit | Win 7 | Both | Both

**Comment by link07** [comment]
Update: I am no longer having this issue, it seems to have been fixed (on windows 8 / chrome 44), will test on windows 7 / chrome 44 when I get back to my desktop :)

**Comment by erengy** [comment]
I can still reproduce the issue on Chrome 44.0.2403.107 and Firefox 41.0a2.

1. Open browser (doesn't matter if I'm logged in or have extensions)
2. Go to https://hummingbird.me/users/erengy/followers
3. Click on any follower's cover image or username

Note that clicking on an avatar doesn't cause the issue; it loads a new page instead. Is this because avatars don't have the `ember-view` class like others? Is this intentional?

**Comment by vevix** [comment]
I'm still having a hard time reproducing this every time and when I do it's
not a clear bug. Hoping the 1.13 update will fix this,  if not I'll fix it
with that update.

**Comment by link07** [comment]
I can still reproduce Chrome 44 / win 7, but it works fine firefox 38 / win 7 and chrome 44 / win 8 :/, I'm fairly sure it's not an addon, because my windows 7 and 8 installs of chrome use the same addons, and its still in issue in incognito.
