### ISSUE TITLE
User icon appears as user name on profile page

### ISSUE THREAD

**Issue by Snitzle** [hummingbird-me/hummingbird#616]
Firefox 39.0.3, Windows 10. This bug has happened consistently since joining the site and obstructs other text in the status updates and anime watch updates. Image of the bug is attached. 

![dxqsy0a](https://cloud.githubusercontent.com/assets/6697359/9212436/b0be63da-4080-11e5-9f16-bf051ed4b4af.png)

**Comment by NuckChorris** [comment]
I had hoped this would go away on its own but @JoshFabian can you clear the CloudFlare cache for the static server

**Comment by JoshFabian** [comment]
Done

**Comment by vevix** [comment]
I believe this is a different issue, I was looking @ a profile that had a caching issue and that was indeed fixed whereas it's still broken for this user.

We force JPG on the `thumb_small` style.

```
thumb_small: {geometry: '100x100#', animated: false, format: :jpg},
```

but the link in the HTML on this users profile is missing an extension. `https://static.hummingbird.me/users/avatars/000/100/705/thumb_small/data?1439290809`

------

I think this is an issue with Facebook accounts.

**Comment by Snitzle** [comment]
Now you have said something I should have mentioned that this is indeed a Facebook account I'm using. I didn't realize it could make a difference.

**Comment by NuckChorris** [comment]
I think we currently have two issues: the caching issue (which has very slowly been fading away) and the Facebook issue. The caching one should be fixed now hopefully
